let stock =[
    {id:1,
    tipo:"calza",
    img:"./img/calzas/calza-amarilla.png",
    color:"amarilla",talle:"S",
    precio:5200,
    cantidad:5},

    {id:2,
    tipo:"calza",
    img:"./img/calzas/calza-celeste.png",
    color:"celeste",
    talle:"M",
    precio:5200,
    cantidad:5},

    {id:3,
    tipo:"calza",
    img:"./img/calzas/calza-rosa.png",
    color:"rosa",
    talle:"XL",
    precio:5200,
    cantidad:5},

    {id:4,
    tipo:"calza",
    img:"./img/calzas/calza-negra.png",
    color:"negra",
    talle:"L",
    precio:5200,
    cantidad:5},

    {id:5,
    tipo:"top",
    img:"./img/tops/conjunto-amarillo.png",
    color:"amarillo",
    talle:"S",
    precio:6500,
    cantidad:5},

    {id:6,
    tipo:"top",
    img:"./img/tops/conjunto-azul.png",
    color:"azul",
    talle:"L",
    precio:6500,
    cantidad:5},

    {id:7,
    tipo:"top",
    img:"./img/tops/conjunto-lila.png",
    color:"lila",
    talle:"XL",
    precio:6500,
    cantidad:5},

    {id:8,
    tipo:"top",
    img:"./img/tops/conjunto-rojo.png",
    color:"rojo",
    talle:"M",
    precio:6500,
    cantidad:5},

]
